### PR TITLE
Fixes & new small Jinja templates

### PR DESCRIPTION
**Pull request by mirceaulinic**
<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

### CODE REVIEW

**Comment by dbarrosop** [comment]
+1

**Comment by ktbyers** [comment]
@mirceaulinic Is there something I am supposed to do on this? It looks like David already approved it.

The unit test failures are probably due to changes in napalm-base.

**Comment by mirceaulinic** [comment]
@ktbyers Only if you could review and check the Cisco syntax

**Comment by ktbyers** [comment]
Okay, sounds good.

**Comment by ktbyers** [comment]
@mirceaulinic 

delete_ntp_peers.j2              GOOD
delete_ntp_servers.j2           GOOD
set_hostname.j2                   GOOD
set_ntp_peers.j2                   GOOD
set_ntp_servers.j2                GOOD

delete_snmp_config.j2         ISSUES (these need to be changed):

```
no snmp-server location
no snmp-server contact
no snmp-server chassis-id
no snmp-server community {{ comm_name }}
```

snmp_config.j2                      ISSUES (issues this needs to be changed):

```
snmp-server community {{ comm_name }} RW
snmp-server community {{ comm_name }} RO
```

**Comment by mirceaulinic** [comment]
Thanks @ktbyers! I've pushed the changes: https://github.com/napalm-automation/napalm-ios/pull/81/commits/16bbb79e40b55b5959f9b32a39c6aed701441d4f

**Pull request merged**
