### PR TITLE
Add VRF support to traceroute and ping on IOS

### PR DESCRIPTION
**Pull request by XioNoX**
Cf. https://github.com/napalm-automation/napalm-base/pull/185 for napalm-base.

Tested on IOS-XE.

### CODE REVIEW

**Comment by XioNoX** [comment]
The travis job probably failed because of the missing napalm-base parts (in a different PR).

**Comment by mirceaulinic** [comment]
Solves https://github.com/napalm-automation/napalm-ios/issues/105

**Comment by ktbyers** [comment]
This looks good from my perspective once this PR is integrated into napalm-base:

https://github.com/napalm-automation/napalm-base/pull/185

Note, napalm-base has to be fully released to pypi.

Also, we need to update requirements.txt to reflect new required napalm-base version.

**Comment by mirceaulinic** [comment]
@XioNoX this branch has some lint fixes needed: https://travis-ci.org/napalm-automation/napalm-ios/jobs/193348500
Please next time avoid editing from the browser!

**Pull request merged**
